FROM alpine:3.20.0
RUN apk add --no-cache git sudo shadow bash go nodejs npm tzdata
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo

WORKDIR /app

RUN groupadd -r -g 1000 user
RUN useradd --create-home -r -u 1000 -g 1000 -s /usr/bin/bash user

# RUN adduser user sudo
RUN echo 'user ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user
CMD bash